In [3]:
import torch
from torch import autograd

In [5]:
x = torch.arange(4).float()
x

tensor([0., 1., 2., 3.])

In [6]:
x.requires_grad_(True)

tensor([0., 1., 2., 3.], requires_grad=True)

In [7]:
y = 2 * torch.dot(x, x.t())

In [8]:
y.backward()

In [9]:
print(x.grad)

tensor([ 0.,  4.,  8., 12.])


In [10]:
print(dir(torch.random))

['Generator', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '_fork_rng_warned_already', 'contextlib', 'default_generator', 'fork_rng', 'get_rng_state', 'initial_seed', 'manual_seed', 'seed', 'set_rng_state', 'torch', 'warnings']
