In [2]:
import torch

print("版本号：{}".format(torch.__version__))

版本号：1.13.1


In [3]:
tensor_a = torch.arange(0, 12)
tensor_a

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
print("张量的存储位置:{}".format(tensor_a.device))

张量的存储位置:cpu


In [7]:
tensor_a.shape

torch.Size([12])

In [9]:
tensor_a.numel()

12

In [10]:
x = tensor_a.view(3, 4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [11]:
torch.zeros(2, 3, 4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
torch.ones(3, 4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [14]:
y = torch.tensor([[2, 1, 3, 4], [1, 2, 3, 4], [3, 5, 6, 7]])
y

tensor([[2, 1, 3, 4],
        [1, 2, 3, 4],
        [3, 5, 6, 7]])

In [15]:
torch.randn(3, 4)

tensor([[-0.5143, -0.3596, -1.1673, -0.7982],
        [ 1.4216,  0.5447, -0.3189,  2.4182],
        [-0.4698,  0.0612, -0.4494,  1.3293]])

In [16]:
x + y

tensor([[ 2,  2,  5,  7],
        [ 5,  7,  9, 11],
        [11, 14, 16, 18]])

In [18]:
x.float() / y.float()

tensor([[0.0000, 1.0000, 0.6667, 0.7500],
        [4.0000, 2.5000, 2.0000, 1.7500],
        [2.6667, 1.8000, 1.6667, 1.5714]])

In [19]:
torch.exp(y.float())

tensor([[   7.3891,    2.7183,   20.0855,   54.5981],
        [   2.7183,    7.3891,   20.0855,   54.5981],
        [  20.0855,  148.4132,  403.4288, 1096.6332]])

In [20]:
x @ y.t()

tensor([[ 19,  20,  38],
        [ 59,  60, 122],
        [ 99, 100, 206]])

In [21]:
torch.cat((x, y), 0), torch.cat((x, y), 1)

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [ 2,  1,  3,  4],
         [ 1,  2,  3,  4],
         [ 3,  5,  6,  7]]),
 tensor([[ 0,  1,  2,  3,  2,  1,  3,  4],
         [ 4,  5,  6,  7,  1,  2,  3,  4],
         [ 8,  9, 10, 11,  3,  5,  6,  7]]))

In [22]:
x == y

tensor([[False,  True, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [23]:
torch.sum(x)

tensor(66)

In [25]:
torch.norm(x.float()).item()

22.494443893432617

# broadcasting

In [27]:
A = torch.arange(0, 3).view(3, 1)
B = torch.arange(0, 2).view(1, 2)
A, B

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [28]:
A + B

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [29]:
# index
x[1:3]


tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [32]:
x[1, 2] = 9
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  9,  7],
        [ 8,  9, 10, 11]])

In [33]:
x[1:2, ] = 12
x

tensor([[ 0,  1,  2,  3],
        [12, 12, 12, 12],
        [ 8,  9, 10, 11]])

In [35]:
# 运算的内存开销

before = id(y)
y = y + x
id(y) == before

False

In [36]:
z = torch.zeros_like(y)
before = id(z)
z[:] = x + y
id(z) == before

True

In [37]:
torch.add(x, y, out=z)
id(z) == before

True

In [38]:
before = id(x)
x += y
id(x) == before

True

In [39]:
# tensor 与numpy相互转换
import numpy as np

p = np.ones((2, 3))
D = torch.from_numpy(p)
D

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [40]:
D.numpy()

array([[1., 1., 1.],
       [1., 1., 1.]])